# fly.toml app configuration file generated for bwki2025-lowres-langid-backend on 2025-09-17T12:30:41Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bwki2025-lowres-langid-backend'
primary_region = 'fra'

[build]

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
memory_mb = 2048

[mounts]
source = "models_vol"
destination = "/models"

[env]
PROJECT_NAME = "bwki2025-lowres-langid-backend"
BACKEND_CORS_ORIGINS = "http://localhost:8000,https://localhost:8000,https://toberocat.github.io"
MODELS_DIR = "/models"
HF_REPO = "Tobero/bwki2025-lowres-langid-model"
HF_REV = "main"
HF_HUB_ENABLE_HF_TRANSFER = 1